services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bnck-admin-catalogo-image:latest
    container_name: bnck-admin-catalogo
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m

